### ISSUE TITLE
Need to add capabilities for using non-A0 stars as telluric standards

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#193]
This is relatively semi-specific case, but if a G-star is observed as the standard (often for asteroids, occasionally for stars), there is a catastrophic failure for "full" telluric correction in SXD mode if no line is found, as there is no way of measuring the instrument broadening profile unless a specific H I line is present. Since this influences a small (but nonzero) set of observations, either a work around that allows the user to use a "library" LSF, or to do a simple ratio with a model, would be helpful here.

**Comment by michaelcushing** [comment]
For the asteroid, you should just be able to use the IP mode (although not ideal).  For the stars, am I allowed to say "take the data like we said, otherwise it isn't our fault if your data sucks!".  You can also use the IP for the stars, although again not ideal.  

Trying to write a similar code for G stars is not really realistic because one would have to adjust the EWs of lots of metal lines (like we do for the H lines for A stars).  

I don't mind thinking about this, but I think there are a lot of other things that are more important to add (after the full code is done of course).  Let's chat Wednesday about where to put it in the list of things to do.

**Comment by michaelcushing** [comment]
I should add that for the asteroid, if you ask the telluric package to do reflectance, does it not work?

**Comment by aburgasser** [comment]
The asteroids are fine for now (although is the telluric shifting included here?), it's a few - unfortunately heavy - users who seem to have opted in for non A0 V standards. I could implement the ratioing with BB correction as an interim approach so we'll just leave this open. Can we fold in telluric correction shift for the ratio part?

**Comment by michaelcushing** [comment]
I am almost finished with the shifting (done by Wed).  I can then quickly add in "ratio" as another mode.

**Comment by michaelcushing** [comment]
I have created a basic mode for the telluric correction which divides by a standard and multiples by a blackbody.
