### ISSUE TITLE
plot_spectrum() returns a matplotlib Axes object - is that the right thing to return?

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#61]
currently plot_spectrum() returns a matplotlib Axes object, which in principle can be manipulated ala:

```
ax = plot_spectra('combspec1-8.fits',colors='k',y="flux and uncertainty",order_numbers=False,display=False)
ax.set_xlabel('Wavelength (micron)', fontsize=15)
ax.set_ylabel('F$_{\lambda}$', fontsize=15)
ax.legend(['Flux','Uncertainty'],fontsize=14)
```
however, not clear how to then "show" the Axes object. If the purpose is to return a plot object for user manipulation, I think we need to return ax.plot() from the code instead (see example in https://matplotlib.org/3.5.0/tutorials/introductory/usage.html#the-object-oriented-interface-and-the-pyplot-interface)

**Comment by michaelcushing** [comment]
When I push the latest one, we can figure this one out.

**Comment by michaelcushing** [comment]
I have updated this program (as we talked about on email).  The default is now to display to the screen and only do the pdf if the pdf info is passed.  It is, however, currently displayed using pl.ion().  See email that I will send in a few.

My goal with this program was not necessarily to let the user muck around with it but rather it be a quick display for our QA purposes.  The titles are set by the FITS file info so that isn't something that would need to be changed (I could make the font size an input parameter).
