### ISSUE TITLE
plot spectra doesn't provide much ability for user to control - suggested mods to keyword inputs

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#62]
A lot of the structure of plot_spectrum is hard coded, with no way for the user to set the xlabel, ylabel, fontsizes, etc. This could be handled with a input dictionary e.g., plot_parameters, that takes these variables as input and passes it along to the plot_aperture function (so that would need modification as well)

The file_info dictionary also appears to be hard-coded to PDF only, but matplotlib can save to many formats (png, pdf, etc.) Seems all we really need here is a keyword to an output file name, and matplotlib will figure it out.

**Comment by michaelcushing** [comment]
I didn't write this function to be used by the user to make figures but rather just a QA plotter.  The labels are drawn from the FITS header but I can add keywords to let the user override them.  I can also add a font size keyword.  

In general, the QA plots can be written to disk in various formats.  I can't remember whether I have that feature actually accessible for the user in the pyspextool_setup routine but I can get that going.  For this one, it was hard coded because for multiple aperture files, they have to be written to a multi-page file and so I just chose pdf.

**Comment by kelle** [comment]
I am also looking into seeing if we can outsource the plotting/visualizing to another package. For the moment, I don't think we should too much time tweaking this particular functionality.
